import Head from 'next/head'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import React, {useState} from "react";
import ApiService from './api.service';



export default function Home() {

  const [label,setLabel] = useState("");
  const [city,setCity] = useState("");

  function sendRequestButton() {
    ApiService.sendRequest(city).then(response => {
      setLabel(response.data.current.temperature);
      console.log(label);
    })
  }
  function handleTextChange(e) {
    setCity(e.target.value);
  }
  return (
    <div>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <TextField onChange= {handleTextChange}></TextField>
        <Button onClick = {sendRequestButton} variant="outlined">Send</Button>
        <h1>{label}</h1>
      </main>

    </div>
  )
}
